package core

internal object Libs {
    const val KOTLIN_MULTIPLATFORM = "kotlin-multiplatform"
    const val JETBRAINS_COMPOSE = "jetbrains-compose"
    const val COMPOSE_COMPILER = "compose-compiler"
    const val KOTLINX_SERIALIZATION = "kotlinx-serialization"
    const val KOTLINX_SERIALIZATION_JSON = "kotlinx-serialization-json"
    const val KTORFIT = "ktorfit"
    const val KTOR_CORE = "ktor-core"
    const val KTOR_LOGGING = "ktor-logging"
    const val KTOR_AUTH = "ktor-auth"
    const val KTOR_NEGOTIATION = "ktor-negotiation"
    const val KTOR_SERIALIZATION = "ktor-serialization"
    const val KTOR_SERIALIZATION_JSON = "ktor-serialization-json"
    const val KSP = "ksp"
    const val BUILDKONFIG = "buildkonfig"
    const val KOIN_CORE = "koin-core"
    const val KOIN_TEST = "koin-test"
    const val KOIN_ANDROID = "koin-android"
    const val DECOMPOSE = "decompose"
    const val DECOMPOSE_COMPOSE = "decompose-compose"
    const val ESSENTY_LIFECYCLE = "essenty-lifecycle"
    const val KERMIT = "kermit"
    const val KOTLINX_COROUTINES = "kotlinx-coroutines"
    const val KOTLINX_DATETIME = "kotlinx-datetime"
    const val DATASTORE = "datastore"
    const val DATASTORE_PREFERENCES = "datastore-preferences"
}
